engines:
  eslint:
    enabled: true
    config:
      config: ./.eslintrc.js
      ignore_warnings: true
  csslint:
    enabled: true
  duplication:
    enabled: true

ratings:
  paths:
    - "public/**/*"
    - "test/**/*"
    - "./*.js"
  exclude_paths:
    - "public/js-es5/**"