engines:
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: true
    config:
      config: ./.eslintrc.js
      ignore_warnings: true
  csslint:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
    - "public/**/*"
    - "test/**/*"
    - "./*.js"
    - "**.css"
  exclude_paths:
    - "public/js-es5/**"