sudo: false
language: node_js
node_js:
- '7'
cache:
  directores:
  - node_modules/
install:
- npm install
- npm install mocha
- npm install chai
notifications:
  email: false
  slack:
    secure: BLFZ6es88OidnNGf2vC5Ewhy90EP4b9dqjjV221OgeXN9qmJHbcDtfCymHnjzNhIAqiZLnELdGPTrYjISlVcFvAG3qKOd+YdpgOi4od/oVk8WEW5eIXPpBxLcd8scI+2C76GDNNfkLPhi7Vi7/8DocyNXwcm9mO3icuHfQEhF39verowCBJlPGosUGw2zcss7spvcGgsgF+WVY6GgZ6LTVe2IsIZEMOX+F6ci5tk/MBT6yIAjYtrc+qeqmHFC1u/fsJG0/9TS3SpOD+kU3UiTCfeJUvsHJQMv1EE4rjuLDeR5IiPEhEF0LVtblLXBCNWnDjePn3F0R1f+kpDMsdghsfw/5dZDAcpkl0e78o35se+Czb9r/yEPOYKiMWzwm6hCi7QrrU/DUtJcxvqBS8FYDlmkYThDHOGiSOLCt7Sln75HxGdPzS1xPPfNq9raWwCAseulknooFHJlGj/8l8jkjXs+gLhI3lyKoiiJhF8HIDCQ84SS+Pl2JsALkNd6dXnxUFeSofOoQA40ewI41m3Oa2MuzQYc8G2J8P7n1zJWrdU3cfqUkkblTLMw/78PjAB8SADTlFCfNjopuyG4somt3A1TLfKy9pVFK3aaNoWuUx4tCisEOQOMQXx/O0lgWC91iUPpZa+kSsSMJvPr0s5Edoxne76Md9oSWjY3dIShCw=
deploy:
  provider: heroku
  api_key:
    secure: uYkzRh7zxrmbj9MKhjSDIabjvJrlthdMtdPRzknMEpmlgQwIfVnUVcZsjB2z7tfbfLFT+UP5hm/7wRHwU1K9jWAzibfWyudDVk8wn0xTtiAnxmABmHt4rsKONpIDlGwrf3wRtVEip/a14CzGBvr8uqYhqk66PsKJGbl0xxJC9aFKt08GkGOft22PoZdwLYAW/KA6bnqyLYAWc+Fa7X86BfEDSvoJGnPlyBU0yhWbPXTOrvoZu7v46oPcofvZBkOqRpLMKi9CQQT1R1YFDXyTk8nqopvIbzBKx4STyjIR46jxpyVTpPCDwNzS2VeeTAlaQWpWKFGSKVy4k5YxWimNON77YsoHndWkFcZWWjKp4NEUMCm190g/Zy6osrIqXFZpcRur18Ivgr90HEq1bmL0fFNIpYNVJKM9GITHT1BsS//VQzuIKM8hXBuIxHXxDvwEovvV63g+g7Pq3zXFJ8k0BLtkTsV4XjO8d8OrBYgu3hG84ldifq29kWauhHcPHkI1zD7g7icpV7GSJLHvZ6M9eXuA7auxQrWOPdc5S046hqyeeFvQnxgwvHIMVcsY8Mb6V1p+JquUWGYZGwTJ/vHvryuFmYngWFoFQ0c4lflcpcEHrCP1nP6lxyScYmp/Z559J8hX6JdcKasf0u1BPJiCB5prm70KXRFtueix4R3TUe8=
  app: 
    staging: unlucky-geniuses-staging
    master: unlucky-geniuses

