sudo: false
language: node_js
node_js:
- '7'
cache:
  directores:
  - "$HOME/google-cloud-sdk/"
  - node_modules/
before_install:
- openssl aes-256-cbc -K $encrypted_9717804cea33_key -iv $encrypted_9717804cea33_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- PATH=$PATH:${HOME}/google-cloud-sdk/bin
- openssl aes-256-cbc -K $encrypted_45d1b36fa803_key -iv $encrypted_45d1b36fa803_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
install:
- gcloud config set project `unlucky-geniuses`
- gcloud components update
script:
- gcloud -q preview app deploy app.yaml --promote
